version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "01:00"
          timezone: "America/New_York"

    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "01:00"
          timezone: "America/New_York"

    - package-ecosystem: "composer"
      directory: "/web/wp-content/themes/base-theme"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "01:00"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "09:00"

    # Terraform
    - package-ecosystem: "terraform"
      directory: "/infrastructure"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "09:00"
