version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "01:00"
          timezone: "America/New_York"
          open-pull-requests-limit: 10
          groups:
          dev-dependencies:
              dependency-type: "development"
              update-types:
                  - "minor"
                  - "patch"
          prod-dependencies:
              dependency-type: "production"
              update-types:
                  - "minor"
                  - "patch"
          labels:
              - "dependencies"
              - "npm"
          commit-message:
          prefix: "chore(deps)"
          reviewers:
              - "nickzou"
          assignees:
              - "nickzou"

    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "01:00"
          timezone: "America/New_York"
      open-pull-requests-limit: 5
      groups:
          wordpress-plugins:
              patterns:
                  - "wpackagist-plugin/*"
              update-types:
                  - "minor"
                  - "patch"
      testing-tools:
          patterns:
              - "*"
          exclude-pattners:
              - "wpackagist-plugin/*"
          update-types:
              - "minor"
              - "patch"
      labels:
          - "dependencies"
          - "composer"
          - "plugins"
      commit-message:
          prefix: "chore(deps)"
      reviewers:
          - "nickzou"
      assignees:
          - "nickzou"

      # Composer (theme)
    - package-ecosystem: "composer"
      directory: "/web/wp-content/themes/base-theme"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "01:00"
      open-pull-requests-limit: 5
      groups:
          theme-dependencies:
              patterns:
                  - "*"
              update-types:
                  - "minor"
                  - "patch"
      labels:
          - "dependencies"
          - "composer"
          - "theme"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "09:00"
      open-pull-requests-limit: 5
      labels:
          - "dependencies"
          - "github-actions"
          - "ci"

    # Terraform
    - package-ecosystem: "terraform"
      directory: "/infrastructure"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "09:00"
      open-pull-requests-limit: 3
      labels:
          - "dependencies"
          - "terraform"
          - "infrastructure"
