---

- name: Add Automator User
  user:
    name: automator
    state: present
    groups: sudo, users
    append: yes
    shell: /bin/zsh
    create_home: yes

- name: Allow Automator passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^automator'
    line: 'automator ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
    
- name: Add Automator's Public Key
  authorized_key:
    user: automator
    state: present
    key: "{{ lookup('file', '~/.ssh/automator.pub') }}"

