name: Hello World Workflow

on:
  # Triggers the workflow on push events
  push:
    branches:
      - "deployment-action"
  pull_request:
    types: [ closed ]
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 'latest'
      #     cache: 'npm'
      #
      # - name: Set up PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '8.2'
      #     tools: composer:v2
      #     coverage: none
      #
      # - name: Install Node dependencies
      #   run: |
      #     npm install
      #
      # - name: Install PHP dependencies
      #   run: |
      #     npm run composer:install:dev
      #     npm run composer:install:theme
      #
      # - name: Build assets
      #   run: |
      #     npm run prod 

      - name: Get remote host key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          cat > ~/.ssh/automator << 'EOL'
          ${{ secrets.SSH_AUTOMATOR_PRIVATE_KEY }}
          EOL
          chmod 600 ~/.ssh/automator
          ssh-keyscan $ssh_host >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/automator
        env:
          ssh_host: ${{ secrets.SSH_HOST }}

      - name: 
        run: |
          ssh automator@$ssh_hot "whoami"
        env:
          ssh_host: ${{ secrets.SSH_HOST }}
            # rsync -vzcr --rsync-path="sudo rsync" automator@${{ secrets.SSH_HOST }}:/opt/wordpress/wordpress/production
            # ssh automator@${{ secrets.SSH_HOST }} "sudo chown -R www-data:www-data /opt/wordpress/wordpress/production"

